config/routes.rb
Rails.application.routes.draw do
  root "bboards#index"

  resources :bboards do
    resources :artists
  end


  resources :artists do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :bboard
  has_many :songs, dependent: :destroy

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/bboard.rb
class Bboard < ApplicationRecord
  has_many :artists, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_bboard
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = @bboard.artists
  end

  def show
  end

  def new
    @artist = @bboard.artists.new
  end

  def create
    @artist = @bboard.artists.new(artist_params)
    
    if @artist.save
      redirect_to [@bboard, @artist]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to [@bboard, @artist]
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to bboard_artists_path
  end

  private

    def set_bboard
      @bboard = Bboard.find(params[:bboard_id])
    end

    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:first_name, :last_name, :avatar)
    end
end

app/controllers/bboards_controller.rb
class BboardsController < ApplicationController
  before_action :set_bboard, only: [:show, :update, :edit, :destroy]

  def index
    @bboards = Bboard.all
  end

  def show
  end

  def new
    @bboard = Bboard.new
  end

  def create
    @bboard = Bboard.new(bboard_params)

    if @bboard.save
      redirect_to bboards_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @bboard.update(bboard_params)
      redirect_to @bboard
    else
      render :edit
    end
  end

  def destroy
    @bboard.destroy
    redirect_to bboards_path
  end

  private

  def set_bboard
    @bboard = Bboard.find(params[:id])
  end

  def bboard_params
    params.require(:bboard).permit(:title, :genre)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.new(song_params)
    
    if @song.save
      redirect_to artist_songs_path(@artist)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to artist_song_path(@artist)
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_songs_path(@artist)
  end

  private

    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:title, :album)
    end
end

app/views/artists/_form.html.erb
<%= form_with(model: [@bboard, @artist], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, placeholder: "First Name", autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.text_field :avatar, required: true, placeholder: "Avatar" %>
  </div>
  <%= f.submit "Submit", class: "ui blue button" %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form", bboard: @bboard, artist: @artist %>
<br />
<%= link_to "Show", bboard_artist_path([@bboard, @artist]) %> |
<%= link_to "Back", bboard_artists_path(@bboard) %>

app/views/artists/index.html.erb
<h1 class="ui header">Artists</h1>
<%= link_to 'Add a new Artist', new_bboard_artist_path(@bboard) %>
<br />
<%= link_to 'Back', bboard_path(@bboard) %>
<div class="ui divider"></div>

<div class="ui grid">
  <% @artists.each do |artist| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
          <img src="https://robohash.org/<%= artist.avatar %>?set=set4" />
        </div>
        <div class="content">
          <%= link_to "#{artist.full_name}", [@bboard, artist], class: "header" %>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
            <div class="ui basic green button">
              <%= link_to 'Edit', edit_artist_path([@bboard, artist]) %>
            </div>
            <div class="ui basic red button">
              <%= link_to 'Delete', [@bboard, artist], method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render "form", bboard: @bboard, artist: @artist %>
<br />
<%= link_to "Back", bboard_artists_path(@bboard) %>

app/views/artists/show.html.erb
<h1 class="ui header"><%= @artist.full_name %></h1>
<div class="ui card">
  <div class="image">
    <img src="https://robohash.org/<%= @artist.avatar %>?set=set4" />
  </div>
  <div class="content">
    <%= link_to 'View Songs', artist_songs_path(@artist) %>
  </div>
</div>

<div class="extra content">
  <div class="ui button">
      <%= link_to 'Edit Artist', edit_bboard_artist_path([@bboard, @artist]) %>
  </div>
  <div class="ui button">
    <%= link_to 'Back to Artists', bboard_artists_path(@bboard) %>
  </div>
</div>

app/views/bboards/_form.html.erb
<%= form_with(model: @bboard, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, required: true, placeholder: "Title", autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre, required: true, placeholder: "Genre" %>
  </div>
  <%= f.submit "Submit", class: "ui blue button" %>
<% end %>

app/views/bboards/edit.html.erb
<h1>Edit Billboard</h1>

<%= render "form", bboard: @bboard %>
<br />
<%= link_to "Show", bboard_path(@bboard) %> |
<%= link_to "Back", bboards_path %>

app/views/bboards/index.html.erb
<h1 class="ui header">Billboard Charts</h1>
<%= link_to 'Create a new Billboard', new_bboard_path %>
<div class="ui divider"></div>

<div class="ui grid">
  <% @bboards.each do |bboard| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="content">
          <%= link_to bboard.title, bboard, class: "header" %>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
            <div class="ui basic green button">
              <%= link_to 'Edit', edit_bboard_path(bboard) %>
            </div>
            <div class="ui basic red button">
              <%= link_to 'Delete', bboard, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bboards/new.html.erb
<h1>New Billboard</h1>

<%= render "form", bboard: @bboard %>
<br />
<%= link_to "Back", bboards_path %>

app/views/bboards/show.html.erb
<h1 class="ui header"><%= @bboard.title %></h1>
<h2 class="ui header">Genre: <%= @bboard.genre %></h2>
<hr />

<div class="ui vertical text menu">
  <div class="header item">Sort By</div>
    <a class="active item">
      <%= link_to 'By Artists', bboard_artists_path(@bboard) %>
    </a>
  </div>
</div>
<br />
<div class="ui container">
  <div class="extra content">
    <div class="ui button">
        <%= link_to 'Edit Billboard', edit_bboard_path(@bboard) %>
    </div>
    <div class="ui button">
      <%= link_to 'Back to Billboards', bboards_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBboards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_with(model: [@artist, @song], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, required: true, placeholder: "Title", autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :album %>
    <%= f.text_field :album, required: true, placeholder: "Album" %>
  </div>
  <%= f.submit "Submit", class: "ui blue button" %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>
<%= render "form", artist: @artist, song: @song %>
<br/>
<%= link_to 'Show', artist_song_path([@artist, @song]) %> |
<%= link_to 'Back', artist_songs_path(@artist) %>

app/views/songs/index.html.erb
<h1 class="ui header">Songs</h1>
<%= link_to 'Add a new Song', new_artist_song_path(@artist) %>
<br />
<div class="ui divider"></div>

<div class="ui grid">
    <% @songs.each do |song| %>
      <div class="sixteen wide mobile eight wide tablet four wide computer column">
        <div class="ui card">
          <div class="content">
            <%= link_to "#{song.title}", [@artist, song], class: "header" %>
          </div>
          <div class="extra content">
            <div class="ui two buttons">
              <div class="ui basic green button">
                <%= link_to 'Edit', edit_artist_song_path(@artist, song) %>
              </div>  
              <div class="ui basic red button">
                <%= link_to 'Delete', [@artist, song], method: :delete, data: { confirm: "Are you sure?" } %>
              </div>            
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>
<%= render 'form', artist: @artist, song: @song %>
<br />
<%= link_to 'Back', artist_songs_path(@artist) %>

app/views/songs/show.html.erb
<div class="ui card">
  <div class="content">
    <p class="header">
      <%= @song.title %>
    </p>
    <div class="description">
      By: <%= @artist.full_name %>
      <br />
      Album: <%= @song.album %>
    </div>
  </div>  
  <div class="extra content">
    <%= link_to 'Edit Song', edit_artist_song_path(@artist, @song) %> |
    <%= link_to 'Back to Songs', artist_songs_path(@artist) %>
  </div>
</div>
<br />
<br />
<div class="ui labeled button" tabindex="0">
  <div class="ui button">
    <i class="heart icon"></i> Like
  </div>
  <a class="ui basic label">
    2,048
  </a>
</div>